linters:
  enable-all: false
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gofumpt

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        files:
          - $all
          - "!$test"
          - "!*_test.go"
        allow:
          - github.com/gin-gonic/gin
          - embed
          - io/fs
          - net/http
          - os
          - path
          - strings
          - fmt

run:
  timeout: 3m