language: go

jobs:
  fast_finish: true
  include:
  - go: 1.16.x
  - go: master

install:
  - go get -t -v -d
  - go get github.com/campoy/embedmd

script:
  - embedmd -w *.md
  - go test -v -covermode=atomic -coverprofile=coverage.out

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/acc2c57482e94b44f557
    on_success: change
    on_failure: always
    on_start: never
